// <auto-generated />
namespace Controllers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_CodMaterial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_CodMaterial));
        
        string IMigrationMetadata.Id
        {
            get { return "201806280113084_Add_CodMaterial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
